project:
  type: website
  output-dir: docs

website:
  title: "Human Ethology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - editors.qmd
      - href: https://ishe.org
        text: ISHE website
        target: blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
