
## About the Journal

*Human Ethology* is the official journal of [The International Society for Human Ethology (ISHE)](https://ishe.org). It is an online peer-reviewed journal publishing scholarly works within the broad tradition of ethology as applied to humans. *Human Ethology* is open-access (CC BY-NC-ND 4.0) and does not charge authors publication fees.

ISHE was founded in 1972 and was producing a newsletter for circulation to members soon thereafter. The *Human Ethology Newsletter* became the *Human Ethology Bulletin* in 1995 and started publishing peer-reviewed scholarly articles in 2012, when the journal also moved to an online format. In 2019, the *Human Ethology Bulletin* was renamed *Human Ethology* and has since continued the practice of publishing one volume per calendar year, utilising the flexibility of the online format to add articles as they are accepted.

Ethology has close ties to many other disciplines including behavioural ecology, evolutionary biology, physical anthropology, cultural anthropology, comparative psychology, developmental psychology, evolutionary psychology, and linguistics.

*Human Ethology* publishes articles in all areas relating to the direct observation of human behaviour and that of closely related species, as well as work taking an approach consistent with Tinbergen’s four levels of explanation. Purely descriptive and inductive studies will also be considered as well as reviews, provided they are thorough and methodologically rigorous. The journal also welcomes submissions relating to the replication of earlier studies.
